server:
  port: 4001

spring:
  application:
    name: auth-service
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: dummyclient
              client-secret: {noop}dummysecret
              client-authentication-methods: client_secret_basic
              authorization-grant-types: 
                - client_credentials
                - authorization_code
                - refresh_token
              redirect-uris: 
                - http://localhost:4000/login/oauth2/code/dummyclient
                - https://oauth.pstmn.io/v1/callback
              scopes:
                - openid
                - profile
                - patient:read
                - patient:create
                - patient:update
                - patient:delete
            require-authorization-consent: false

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: admin
    password: strongpass
