pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                dir('auth-service') {
                    sh  """
                    echo Test
                    """
                }
            }
        }
    }
}
