pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = '783951397575'
        AWS_REGION = 'us-east-1'
        ECR_REPOSITORY = 'auth-service-repository'
        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {
        stage('Build') {
            steps {
                dir('auth-service') {
                    sh """
                    docker build \
                    --provenance=false \
                    -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_NUMBER} \
                    .
                    """
                }
            }
        }

        stage('Push to ECR') {
            steps {
                sh """
                aws ecr get-login-password \
                --region ${AWS_REGION} \
                | docker login \
                --username AWS \
                --password-stdin ${ECR_REGISTRY}\

                docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_NUMBER}
                """
            }
        }
    }

}
