pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('auth-service') {
                    sh """
                    docker build -t auth-service:${BUILD_NUMBER} .
                    """
                }
            }
        }
    }
}
